"""Real WordPress admin checks in a disposable CI site. No production URLs accepted."""
import json
import os
import pathlib
import shutil
from playwright.sync_api import sync_playwright, expect

assert os.environ.get('GITHUB_ACTIONS') == 'true'
assert os.environ.get('ECD_INTEGRATION_DISPOSABLE') == '1'
base = 'http://localhost:8081'
evidence = pathlib.Path(os.environ['RUNNER_TEMP']) / 'admin-evidence'
evidence.mkdir(exist_ok=True)
checks = []
errors = []

def check(value, name):
    if not value:
        raise AssertionError(name)
    checks.append(name)

with sync_playwright() as p:
    executable = shutil.which('google-chrome') or shutil.which('chromium')
    assert executable, 'A real Chromium/Chrome binary is required; no skipped browser gate.'
    browser = p.chromium.launch(executable_path=executable, args=['--no-sandbox'])
    context = browser.new_context(viewport={'width': 1440, 'height': 1000}, reduced_motion='reduce')
    page = context.new_page()
    page.on('pageerror', lambda e: errors.append(str(e)))
    page.on('dialog', lambda d: d.accept() if d.type == 'beforeunload' else d.dismiss())
    requests = []
    page.on('request', lambda request: requests.append(request.url))
    page.goto(base + '/wp-login.php')
    page.locator('#user_login').fill('ci-admin')
    page.locator('#user_pass').fill(os.environ['ECD_BROWSER_PASSWORD'])
    page.locator('#wp-submit').click()
    page.wait_for_url('**/wp-admin/**')
    check(page.locator('[href*="assets/admin.css"]').count() == 0, 'no custom admin CSS on Dashboard')
    check(page.locator('[src*="assets/admin.js"]').count() == 0, 'no custom admin JS on Dashboard')
    page.goto(base + '/wp-admin/admin.php?page=ecd-timers')
    expect(page.locator('.email-countdown-admin')).to_be_visible()
    check(page.locator('.email-countdown-admin img').count() == 0, 'list contains no generated image thumbnails')
    check(page.locator('[href*="assets/admin.css"]').count() == 1, 'exactly one plugin stylesheet')
    check(page.locator('[src*="assets/admin.js"]').count() == 1, 'exactly one plugin script')
    page.get_by_role('link', name='Create Timer', exact=True).click()
    page.locator('#ect-timer_id').fill('browser-test')
    page.locator('#ect-deadline').fill('2030-12-31T23:59:59')
    page.get_by_text('Custom Labels', exact=True).click()
    page.locator('#ect-label_d').fill('Campaign days')
    page.locator('#ect-label_h').fill('')
    page.get_by_text('Typography and Size', exact=True).click()
    page.locator('#ect-size_digit').fill('201')
    page.locator('#ect-editor button[type=submit]').click()
    expect(page.locator('#ect-errors')).to_be_visible()
    check(page.locator('#ect-errors').evaluate('(e)=>e===document.activeElement'), 'invalid form moves focus to summary')
    expect(page.locator('#ect-size_digit')).to_have_attribute('aria-invalid', 'true')
    check(page.locator('#ect-label_d').input_value() == 'Campaign days', 'client error retains custom label')
    page.locator('#ect-size_digit').fill('40')
    page.locator('#ect-editor button[type=submit]').click()
    page.wait_for_url('**edit=browser-test**')
    expect(page.get_by_text('Timer saved.', exact=True)).to_be_visible()
    check(page.locator('#ect-timer_id').get_attribute('readonly') is not None, 'saved ID is read-only')
    page.get_by_text('Custom Labels', exact=True).click()
    check(page.locator('#ect-label_h').input_value() == '', 'empty label roundtrips through actual database')
    page.get_by_text('Custom Labels', exact=True).click()
    check('mode=static' in page.locator('#ect-preview').get_attribute('src'), 'saved preview initially static')
    expect(page.locator('#ect-preview')).to_have_js_property('complete', True)
    check(page.locator('#ect-preview').evaluate('(e)=>e.naturalWidth>1'), 'saved preview is a real rendered image')
    page.locator('#ect-animation').click()
    check('mode=email' in page.locator('#ect-preview').get_attribute('src'), 'animation only after explicit action')
    page.locator('#ect-animation').click()
    check('mode=static' in page.locator('#ect-preview').get_attribute('src'), 'Stop returns to static image')
    page.locator('#ect-embed-format').select_option('html')
    code = page.locator('#ect-embed-code').input_value()
    check('<img ' in code and '<p>Ends:' in code and 'Europe/Warsaw' in code, 'email HTML includes alt/deadline/zone')
    page.locator('#ect-embed-format').select_option('shortcode')
    check(page.locator('#ect-embed-code').input_value() == '[ecd_timer id="browser-test"]', 'unchanged shortcode contract')
    page.evaluate("Object.defineProperty(navigator,'clipboard',{value:{writeText:async()=>{throw new Error('denied')}},configurable:true})")
    page.locator('#ect-copy').click()
    expect(page.locator('#ect-copy-result')).to_contain_text('Copy was unavailable')
    check(page.locator('#ect-embed-code').evaluate('(e)=>e.selectionEnd===e.value.length'), 'denied clipboard has selected-text fallback')
    # Check semantics inside the plugin, not unrelated WordPress core controls.
    missing = page.locator('.email-countdown-admin input:not([type=hidden]),.email-countdown-admin select,.email-countdown-admin textarea').evaluate_all('(es)=>es.filter(e=>!e.labels.length).map(e=>e.id)')
    check(not missing, 'every plugin form control has a real label')
    bad_refs = page.locator('.email-countdown-admin [aria-describedby],.email-countdown-admin [aria-labelledby]').evaluate_all("(es)=>es.flatMap(e=>['aria-describedby','aria-labelledby'].flatMap(a=>(e.getAttribute(a)||'').split(/\\s+/).filter(id=>id&&!document.getElementById(id))))")
    check(not bad_refs, 'all ARIA references resolve')
    for width in (320, 375, 768, 1440):
        page.set_viewport_size({'width': width, 'height': 1000})
        check(page.locator('.email-countdown-admin').evaluate('(e)=>e.scrollWidth<=e.clientWidth+1'), f'plugin editor reflow at {width}px')
    page.set_viewport_size({'width': 1440, 'height': 1000})
    page.evaluate('window.scrollTo(0, 0)')
    page.screenshot(path=str(evidence / 'editor.png'), full_page=True)
    page.set_viewport_size({'width': 375, 'height': 1000})
    page.evaluate('window.scrollTo(0, 0)')
    page.screenshot(path=str(evidence / 'editor-mobile.png'), full_page=True)
    page.set_viewport_size({'width': 1440, 'height': 1000})
    page.get_by_text('Delete Timer', exact=True).click()
    page.locator('[name=confirm_delete]').check()
    page.locator('#ect-delete button').click()
    expect(page.locator('#ect-delete-dialog')).to_be_visible()
    check(page.locator('#ect-delete-cancel').evaluate('(e)=>e===document.activeElement'), 'delete dialog initially focuses Cancel')
    page.keyboard.press('Escape')
    expect(page.locator('#ect-delete-dialog')).not_to_be_visible()
    check(page.locator('#ect-delete button').evaluate('(e)=>e===document.activeElement'), 'Escape restores focus to trigger')
    # Real server validation: invalid time zone is not a native browser constraint.
    page.locator('#ect-tz').fill('not/a-zone')
    page.locator('#ect-editor button[type=submit]').click()
    expect(page.locator('#ect-tz')).to_have_attribute('aria-invalid', 'true')
    check(page.locator('#ect-label_h').input_value() == '', 'server error preserves empty labels')
    check(page.locator('#ect-tz').input_value() == 'not/a-zone', 'server error preserves offending input')
    page.locator('#ect-tz').fill('Europe/Warsaw')
    page.locator('#ect-editor button[type=submit]').click()
    expect(page.get_by_text('Timer saved.', exact=True)).to_be_visible()
    page.emulate_media(forced_colors='active')
    page.locator('#ect-tz').focus()
    check(page.locator('#ect-tz').evaluate('(e)=>getComputedStyle(e).outlineStyle') != 'none', 'forced-colors focus remains visible')
    page.emulate_media(forced_colors='none')
    # An independent no-JS context verifies native forms and manual copy.
    nojs = browser.new_context(storage_state=context.storage_state(), java_script_enabled=False, viewport={'width': 1440, 'height': 1000})
    plain = nojs.new_page()
    plain.goto(base + '/wp-admin/admin.php?page=ecd-timers&edit=browser-test')
    check(plain.locator('#ect-animation').is_hidden(), 'no-JS view does not expose inert animation control')
    expect(plain.locator('#ect-label_s')).to_be_visible()
    plain.locator('#ect-label_s').fill('No-JS seconds')
    plain.locator('#ect-editor button[type=submit]').click()
    expect(plain.get_by_text('Timer saved.', exact=True)).to_be_visible()
    check(plain.locator('#ect-label_s').input_value() == 'No-JS seconds', 'native no-JS form persists values')
    check(plain.locator('[data-ect-manual]').get_attribute('open') is not None, 'no-JS manual formats are expanded by default')
    plain.locator('#ect-manual-html').focus()
    plain.keyboard.press('Control+a')
    check(plain.locator('#ect-manual-html').evaluate('(e)=>e.selectionEnd===e.value.length'), 'no-JS manual code can be selected by keyboard')
    plain.screenshot(path=str(evidence / 'editor-no-js.png'), full_page=True)
    expect(plain.locator('#ect-manual-html')).to_be_visible()
    check('2030-12-31' in plain.locator('#ect-manual-html').input_value(), 'no-JS manual email code includes deadline')
    nojs.close()
    page.goto(base + '/wp-admin/admin.php?page=ecd-timers&edit=browser-test')
    page.get_by_text('Delete Timer', exact=True).click()
    page.locator('[name=confirm_delete]').check()
    page.locator('#ect-delete button').click()
    page.locator('#ect-delete-confirm').click()
    page.wait_for_url('**status=deleted**')
    expect(page.get_by_text('Timer deleted.', exact=True)).to_be_visible()
    check(page.locator('code', has_text='browser-test').count() == 0, 'confirmed delete actually removes timer')
    page.goto(base + '/wp-admin/admin.php?page=email-countdown-timer-data')
    check(page.locator('[href*="assets/admin.css"]').count() == 1, 'Data Settings shares scoped styling')
    check(not page.locator('[name=delete_data_on_uninstall]').is_checked(), 'uninstall opt-in remains off')
    check(not errors, 'no browser JavaScript exceptions')
    check(not any('fonts.googleapis.com' in u or 'fonts.gstatic.com' in u for u in requests), 'zero Google Fonts requests')
    report = {'checks': checks, 'count': len(checks), 'browser': browser.version, 'wordpress_site': 'disposable localhost only', 'js_errors': errors, 'limits': 'Custom browser checks; not a screen-reader audit, full axe scan or WCAG certification.'}
    (evidence / 'browser-checks.json').write_text(json.dumps(report, indent=2) + '\n')
    browser.close()
print(f'PASS {len(checks)} real WordPress browser checks')
